name: cocktails
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.0-11.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  #net
  http: ^0.13.4
  dio: ^5.1.2
  dio_smart_retry: ^5.0.0
  json_serializable: ^6.5.4

  #navigation
  auto_route: ^7.4.0

  #logic
  flutter_bloc: ^8.1.2
  bloc_concurrency: ^0.2.2
  path_provider: ^2.0.12
  path: 1.8.3

  #di
  injectable: ^2.1.2
  get_it: ^7.2.0


  #drift
  drift: ^2.9.0
  sqlite3_flutter_libs: ^0.5.0

  #firebase
  firebase_crashlytics: ^3.0.14
  firebase_core: ^2.4.1
  firebase_analytics: ^10.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  freezed: ^2.3.2
  auto_route_generator: 7.0.0
  build_runner:
  drift_dev: ^2.9.0
  injectable_generator: ^2.1.6


flutter:
  uses-material-design: true
